import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Slots are now generated by a job that re-runs (every interval, on every
 * api instance), so "one slot per (location, start_time)" has to be enforced
 * by Postgres for `INSERT ... ON CONFLICT DO NOTHING` to be idempotent. The
 * unique index replaces the plain one from the initial migration -- it
 * serves the same `(location_id, start_time)` lookups.
 *
 * Fails if existing rows already duplicate a (location, start) pair. Resolve
 * those by hand first: delete the duplicate that has no reservations
 * (`reservations.slot_id` is ON DELETE RESTRICT, so Postgres refuses to
 * delete one that does).
 */
export class UniqueSlotStartPerLocation1789824999000 implements MigrationInterface {
  name = 'UniqueSlotStartPerLocation1789824999000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE UNIQUE INDEX uq_slots_location_start ON slots(location_id, start_time);`,
    );
    await queryRunner.query(`DROP INDEX idx_slots_location_start;`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE INDEX idx_slots_location_start ON slots(location_id, start_time);`,
    );
    await queryRunner.query(`DROP INDEX uq_slots_location_start;`);
  }
}
